//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiftingBoard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public int Id { get; set; }
        public string memberId { get; set; }
        public int BoardId { get; set; }
        public bool IsActive { get; set; }
        public bool isCoremember { get; set; }
        public string corememberId { get; set; }
    
        public virtual Board Board { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
