//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiftingBoard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Conversation
    {
        public int ID { get; set; }
        public string Msg { get; set; }
        public string MsgDate { get; set; }
        public string SenderID { get; set; }
        public string ReceiverID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
    }
}
